// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7EBukxOrI5PQ5RHYMIzifzzdIn9A7W7c',
    appId: '1:732815650866:web:f8d09f16b5d30bcfa4cc2b',
    messagingSenderId: '732815650866',
    projectId: 'clouds-2af51',
    authDomain: 'clouds-2af51.firebaseapp.com',
    storageBucket: 'clouds-2af51.firebasestorage.app',
    measurementId: 'G-RE6PMQV4YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9C6pSJTwqAwt8ZGrnExlbP0KFNAvYMWk',
    appId: '1:732815650866:android:f10ed9e55d0c15b8a4cc2b',
    messagingSenderId: '732815650866',
    projectId: 'clouds-2af51',
    storageBucket: 'clouds-2af51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12izMM8LK7TnP8f0r6V0F5jS5IlhshH0',
    appId: '1:732815650866:ios:b9f226721e7d2d79a4cc2b',
    messagingSenderId: '732815650866',
    projectId: 'clouds-2af51',
    storageBucket: 'clouds-2af51.firebasestorage.app',
    iosBundleId: 'com.example.clouds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12izMM8LK7TnP8f0r6V0F5jS5IlhshH0',
    appId: '1:732815650866:ios:b9f226721e7d2d79a4cc2b',
    messagingSenderId: '732815650866',
    projectId: 'clouds-2af51',
    storageBucket: 'clouds-2af51.firebasestorage.app',
    iosBundleId: 'com.example.clouds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7EBukxOrI5PQ5RHYMIzifzzdIn9A7W7c',
    appId: '1:732815650866:web:bbda81d637c6f2dda4cc2b',
    messagingSenderId: '732815650866',
    projectId: 'clouds-2af51',
    authDomain: 'clouds-2af51.firebaseapp.com',
    storageBucket: 'clouds-2af51.firebasestorage.app',
    measurementId: 'G-HZVCN7TLJY',
  );
}
